### ISSUE TITLE
Extraction Fails - RAR archive support: CRARControl::GetPassword: invalid data

### ISSUE THREAD

**Issue by zach-morris** [xbmc/vfs.rar#69] opened 2020-03-19 23:31 UTC
Using Matrix / vfs.rar 3.1.4 attempting to extract an archive results in:

```
ERROR: AddOnLog: RAR archive support: CRARControl::GetPassword: invalid data (no/invalid data file found at '/Users/xxx/Library/Application Support/Kodi/userdata/addon_data/vfs.rar//rar-control.xml')
```

**Comment by bluboyo** [comment] 2020-03-20 08:20
I have the same problem in 18.6, 2.2.2

**Comment by AlwinEsch** [comment] 2020-03-20 11:08
This log mesage is a bug brought by me and becomes fixed.

This error is due to the fact that no password has been used yet and addon tries to tidy up existing ones when closing, logically it then lacks this xml.

Think extracting worked?

**Comment by bluboyo** [comment] 2020-03-20 12:03
Extracting worksDen 20 mars 2020 12:08 skrev Alwin Esch <notifications@github.com>:
This log mesage is a bug brought by me and becomes fixed.
This error is due to the fact that no password has been used yet and addon tries to tidy up existing ones when closing, logically it then lacks this xml.
Think extracting worked?

**Comment by zach-morris** [comment] 2020-03-20 13:52
> This log mesage is a bug brought by me and becomes fixed.
> 
> This error is due to the fact that no password has been used yet and addon tries to tidy up existing ones when closing, logically it then lacks this xml.
> 
> Think extracting worked?

Extract doesn't work.  It fails here before extraction occurs (testing with [this](https://github.com/zach-morris/script.module.archive_tool) new module, which i'll try and submit to the Kodi repo after testing)

**Comment by highlandr** [comment] 2020-04-04 20:10
It's been a pain since the rar is out of the core.
I have the same problem and more... Like I said in the Kodi forum, Alwin, it's impossible to unrar, I can make the dialog.browse, choose the file from rar but then no extraction ... I have my script ready for v19 but I can't extract multi dirs with files properly. If it's a simple rar with 4 .srt files inside it's ok. Multi dirs and multi files just does not work.
If you want a sample, again, tell me.
Thanks!

Regards.

**Comment by AlwinEsch** [comment] 2020-04-04 20:23
At the moment I have not direct time for them, but I look the next days what happens there.

**Comment by AlwinEsch** [comment] 2020-04-05 01:41
Have looked and found source of two bugs:
- If on RAR with multiple packages file (.rar.001...) one was missing was come a crash
- Seen here https://github.com/xbmc/vfs.rar/blob/Leia/src/RarFile.cpp#L52 that the file length is only 128 bytes (there since the addon exists) where can be a bit less. For a unkown reason has it worked by me where the complete test path has >400 characters.

Will look further to find something else.

**Comment by AlwinEsch** [comment] 2020-04-05 06:24
@zach-morris and @highlandr if you use Matrix can you test with them from here https://github.com/xbmc/vfs.rar/pull/75 / https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Fvfs.rar/detail/PR-75/1/artifacts still not finished, but include few fixes and improvement.

Maybe something now works better. Later (on this day) I look further about another problems.

**Comment by highlandr** [comment] 2020-04-05 18:36
Hello Alwin, i've tried that last code but the error is the same.
Allow me to show you a screenshot and a bit of the debug code. Plus the rar file.
![bad_rar](https://user-images.githubusercontent.com/667083/78506794-11658900-7774-11ea-9812-61fb0e3fb698.png)

With this piece of code -> (cdirs, cfiles) = xbmcvfs.listdir(src)
The return is this:
2020-04-05 19:27:47.892 T:38852   DEBUG: ### [LegendasDivx.com] - CDIRS: '['WEBRip - Sincronia 1', 'BluRay', 'WEBRip - Sincronia 2']'
2020-04-05 19:27:47.892 T:38852   DEBUG: ### [LegendasDivx.com] - CFILES: '['BluRay', 'WEBRip - Sincronia 1', 'WEBRip - Sincronia 2']'

Rar file [HERE](https://gameover.com.pt/badrar.rar)

So the vfs.rar thinks the directories are files as well ... and it crashes. Its returns the directories as dirs and files ... Can't get it extracted not event when you just browse the rar and choose the file to append to the movie...
If it's a file without directories it will work fine.

Thanks.

**Comment by AlwinEsch** [comment] 2020-04-06 03:30
Have added there a commit to fix it https://github.com/xbmc/vfs.rar/pull/75/commits/e79daebd54523fd9be7b5e224ad0a807bd9e3966
This RAR has special file/dir flags where the addon was confused.

Also for here the following, not sure if Kodi exited and crashed with them, here it has only brought as very big bug of show.

Had some times that crash was referred to, but was different.

| Type | Desc.
|----|-----------------------
| Crash | Kodi suddenly ends and is completely gone
| Frezze | Kodi runs and is displayed, but can no longer be used and controlled or e.g. a process is shown that never ends.
| Bug | Everything continues to run, only certain things cannot be carried out, e.g. sudden termination of playback, incorrect display, file opening not working.

**Comment by highlandr** [comment] 2020-04-06 07:59
Hello @AlwinEsch, it Frezzes Kodi, I have to go to the taskbar and end the process or Kodi will not run at all.
I will check "Jenkins" for latest compilation.
Thanks.

**Comment by highlandr** [comment] 2020-04-06 08:15
Here's the result:
2020-04-06 09:05:12.748 T:104   DEBUG: ### [LegendasDivx.com] - CDIRS: '['WEBRip - Sincronia 1', 'BluRay', 'WEBRip - Sincronia 2']'
2020-04-06 09:05:12.748 T:104   DEBUG: ### [LegendasDivx.com] - CFILES: '[]'

Comparing with the previous now it doesn't parse the directories as files but it's empty when you browse the RAR file and of course doesn't extract anything.
Here's part of the [LOG](https://gameover.com.pt/temp.zip)
Here's another bad rar file [badrar1.rar](https://gameover.com.pt/badrar1.rar)
Now it does not Freeze. It's a BUG.
Thanks @AlwinEsch for the work and help you committing.

**Comment by AlwinEsch** [comment] 2020-04-06 19:12
I look ahead, just somehow it looked ok with me.
You use Windows, then I look more about them. 

Also to be sure has you used latest from here https://github.com/xbmc/vfs.rar/pull/75 with the **"cleanup back slashes into forward slashes change"** inside.
Has seen on last Windows check that something was wrong with "blackslash"

![Bildschirmfoto von 2020-04-06 21-06-54](https://user-images.githubusercontent.com/6879739/78595617-9c18b780-784a-11ea-94b8-0bfce03720b4.png)
![Bildschirmfoto von 2020-04-06 20-54-19](https://user-images.githubusercontent.com/6879739/78595473-53f99500-784a-11ea-9c7e-7fee2983b8d9.png)
![Bildschirmfoto von 2020-04-06 20-54-28](https://user-images.githubusercontent.com/6879739/78595481-56f48580-784a-11ea-8c8d-2fafee136c04.png)

**Comment by highlandr** [comment] 2020-04-06 19:42
Hello.
Here's a capture of the happening: [HERE](https://gameover.com.pt/kodi_cap1.mp4)
![kodi_vfsrar](https://user-images.githubusercontent.com/667083/78597968-535eff80-7846-11ea-9ad0-845680f13c19.png)
I'm using the latest I think, check the picture, the date of the files.
I grab the files here -> https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Fvfs.rar/detail/PR-75/5/artifacts
The LOG from now [HERE](https://gameover.com.pt/kodi_alita.zip)
If you need more help tell me, I'm online and I'll give you direct details for chat.
Thanks.

**Comment by AlwinEsch** [comment] 2020-04-06 21:19
Thing you have the latest, but seen also now  on your log, that it seems by you on Windows still have problems with the slash `/` and backslash `\`.

Thats also then the reason why it runs on my Linux, but not on Windows.
The path I taken for test on Windows was on a bit different place, maybe thats the reason why it has worked by me.

I look then to make always a whole slash translation to make sure it is correct.

**Comment by AlwinEsch** [comment] 2020-04-06 23:51
Can you try now with this test build:
Leia: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Fvfs.rar/detail/PR-77/3/artifacts
Matrix: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Fvfs.rar/detail/PR-75/8/artifacts

**Comment by zach-morris** [comment] 2020-04-07 03:12
Even in vfs.libarchive, there is a trailing slash issue.  In python I can get the path to work as expected with [this line](https://github.com/zach-morris/script.module.archive_tool/blob/master/lib/archive_tool/archive_tool.py#L185).

**Comment by highlandr** [comment] 2020-04-07 07:02
Good morning Alwin.
I saw you converted everything to forward slash, unfortunately it doesn't work yet.

KODI19
Here's the logs for 2 sample movies, [HERE](https://gameover.com.pt/kodi_alita1.zip) and [HERE](https://gameover.com.pt/kodi_fast.zip).

KODI18
Not working either, logs [HERE](https://gameover.com.pt/kodi18_alita.zip)

Thanks.

**Comment by AlwinEsch** [comment] 2020-04-07 08:39
@highlandr is there possible to become access to https://www.legendasdivx.pt/ and OK from your side?

If yes then I try to send a message to https://www.legendasdivx.pt/forum/memberlist.php?mode=contactadmin and to ask about access (from Germany) for test purpose.

Seen that normal register is limited to Portugal and Brasil.

**EDIT:** Want reproduce the fault 1:1 like by you and to see what exact happens 😄

**Comment by highlandr** [comment] 2020-04-07 09:14
Alwin I just registered with your email on your website.
Check if you get the activation.

**Comment by AlwinEsch** [comment] 2020-04-07 12:08
Crazy, what I try it works 😒 
Was running with code before request, with request and request without the "back slash" thing

![Unbenannt](https://user-images.githubusercontent.com/6879739/78667150-b8fbcc00-78d8-11ea-9f48-166f6183f6cf.JPG)

Will try to test more and hope the error comes.

**Comment by AlwinEsch** [comment] 2020-04-07 12:19
Tested now with them on your Log there comes the error, there seems a bit differences between the RAR Packages. 

Have now something to see and to fix 😄 .

**Comment by highlandr** [comment] 2020-04-07 12:33
Ah! was getting mad at my pc's :) heh
Hope you can fix and yes the new RAR packages are the problem.
You choose an old one first which was ok, the spider one.
Thanks.

**Comment by AlwinEsch** [comment] 2020-04-07 17:47
Think to have fixed now and thing to bring in. 
Maybe still some other things but then are the bugs more less.

Here for test:
- **Matrix:** https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Fvfs.rar/detail/PR-75/10/artifacts
- **Leia:** https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Fvfs.rar/detail/PR-77/6/artifacts

**Comment by highlandr** [comment] 2020-04-07 17:55
Great.
Let me test it out.

**Comment by highlandr** [comment] 2020-04-07 18:19
It works, I can get the file from one of the problematic RARs.
Now I need to check my code :)
I'll keep you posted if anything wrong is found.
Many thanks Alwin.
Btw I tested in Matrix.

**Comment by AlwinEsch** [comment] 2020-04-07 20:01
The new version is released and this should fixed:
- 3.3.0-Matrix
- 2.3.0-Leia

**Closed as completed by AlwinEsch** 2020-04-07 20:01 UTC

**Comment by AlwinEsch** [comment] 2020-04-07 20:40
Thanks a lot @highlandr, with your help was it possible to find the bug.

**Comment by zach-morris** [comment] 2020-04-08 00:04
It works!  There's a test script in the settings for [this module](https://github.com/zach-morris/script.module.archive_tool) which tests all possible archive types with vfs.libararchive _and_ vfs.rar now, including solid files, and it passed on all of them (except iso, but thats because vfs.libarchive currently doesn't list it as a valid filetype) - I was able to use vfs.rar by temporarily disabling vfs.libarchive (using jsonrpc calls) and then re-enabling it after use.

**Comment by highlandr** [comment] 2020-04-08 21:23
Zach get your lib in the official repo so I can use it in my plugin.

**Comment by zach-morris** [comment] 2020-04-09 04:03
Yes, I'll work on that.
